# Generated by Django 6.0.4 on 2026-04-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='qualidade',
        ),
        migrations.DeleteModel(
            name='Qualidade',
        ),
    ]
