# Generated by Django 6.0.4 on 2026-04-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_produto_qualidade_delete_qualidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='produto',
        ),
    ]
